import { Transaction, Budgets, Alert, TranslationSet } from './types';

export const RECEIPT_PRESETS = [
  { merchant: "Restoran Ali Maju Mamak", amount: 12.50, category: "Food & Dining", confidence: 94 },
  { merchant: "MyRapid Bus KL", amount: 2.10, category: "Transport", confidence: 98 },
  { merchant: "Lotus's Ara Damansara", amount: 67.80, category: "Shopping", confidence: 91 },
  { merchant: "Unifi Monthly Bill", amount: 89.00, category: "Bills", confidence: 97 },
  { merchant: "TGV Cinemas 1Utama", amount: 23.00, category: "Entertainment", confidence: 89 },
  { merchant: "KK Super Mart UMS", amount: 18.30, category: "Food & Dining", confidence: 93 },
];

export const DEFAULT_TRANSACTIONS: Transaction[] = [
  { id: "1", merchant: "Restoran Ali Maju", amount: 12.50, date: "2025-06-01", category: "Food & Dining", notes: "Dinner with friends", source: "manual" },
  { id: "2", merchant: "MyRapid Bus", amount: 2.10, date: "2025-06-02", category: "Transport", notes: "Bus fare to campus", source: "manual" },
  { id: "3", merchant: "Lotus's Ara Damansara", amount: 67.80, date: "2025-06-03", category: "Shopping", notes: "Monthly groceries", source: "manual" },
  { id: "4", merchant: "Unifi Monthly", amount: 89.00, date: "2025-06-05", category: "Bills", notes: "Broadband subscription", source: "manual" },
  { id: "5", merchant: "TGV Cinemas", amount: 23.00, date: "2025-06-07", category: "Entertainment", notes: "Movie night", source: "manual" },
  { id: "6", merchant: "KFC Mid Valley", amount: 25.90, date: "2025-06-08", category: "Food & Dining", notes: "Lunch snack", source: "ocr" },
  { id: "7", merchant: "Grab Ride", amount: 15.00, date: "2025-06-10", category: "Transport", notes: "Ride to clinic", source: "manual" },
  { id: "8", merchant: "Popular Bookstore", amount: 45.00, date: "2025-06-11", category: "Shopping", notes: "Reference books for exam", source: "ocr" },
  { id: "9", merchant: "Tenaga Nasional", amount: 110.00, date: "2025-06-12", category: "Bills", notes: "Electricity bill share", source: "manual" },
  { id: "10", merchant: "FamilyMart UM", amount: 14.20, date: "2025-06-14", category: "Food & Dining", notes: "Oden snack", source: "ocr" },
  { id: "11", merchant: "Tealive", amount: 9.50, date: "2025-06-15", category: "Food & Dining", notes: "Boba milk tea", source: "manual" },
  { id: "12", merchant: "Decathlon MY", amount: 85.00, date: "2025-06-15", category: "Shopping", notes: "Sportswear", source: "ocr" },
  { id: "13", merchant: "RapidKL LRT", amount: 3.50, date: "2025-06-16", category: "Transport", notes: "LRT to KL Sentral", source: "manual" },
  { id: "14", merchant: "Watson's Pharmacy", amount: 32.40, date: "2025-06-17", category: "Shopping", notes: "Hygiene products", source: "manual" },
  { id: "15", merchant: "Mamak Ali UM", amount: 8.00, date: "2025-06-18", category: "Food & Dining", notes: "Roti canai and teh tarik", source: "manual" }
];

export const DEFAULT_BUDGETS: Budgets = {
  "Food & Dining": 300.0,
  "Transport": 100.0,
  "Shopping": 200.0,
  "Bills": 150.0,
  "Entertainment": 100.0,
  "Other": 50.0
};

export const DEFAULT_ALERTS: Alert[] = [
  { id: "a1", type: "Overspend Warning", category: "Shopping", amount: 67.80, date: "2025-06-03", severity: "Medium", dismissed: false },
  { id: "a2", type: "Unusual Spike", category: "Entertainment", amount: 23.00, date: "2025-06-07", severity: "High", dismissed: false },
];

export const TRANSLATIONS: { en: TranslationSet; bm: TranslationSet } = {
  en: {
    dashboard: "🏠 Dashboard",
    receiptEntry: "🧾 Receipt & Transaction Entry",
    transactions: "🔀 Transaction & Category Management",
    budgets: "🎯 Budget Goal Management",
    reports: "📊 Spending Reports",
    forecastAlerts: "🤖 AI Forecast & Alerts",
    logoSubtitle: "Intelligent Expense",
    userId: "Amirul Syafiq — UM Student • 21 y/o",
    langToggle: "Bahasa Malaysia (BM)",
    totalSpentThisMonth: "Total Spent This Month",
    budgetRemaining: "Budget Remaining",
    txThisWeek: "Transactions This Week",
    activeAlerts: "Active Alerts",
    spendingByCategory: "Spending by Category",
    budgetVsActual: "Budget vs Actual per Category",
    recentTransactions: "Recent Transactions",
    viewAll: "View All Transactions",
    uploadReceipt: "📤 Upload Receipt",
    ocrTab: "🔍 OCR Receipt Upload",
    manualTab: "✏️ Manual Data Form",
    uploadReceiptLabel: "Upload your receipt (Drag & Drop or Browse)",
    cameraInputLabel: "Or take a photo of your receipt",
    extractingSpinner: "Extracting receipt data with Gemini OCR...",
    ocrResult: "OCR Result",
    merchantName: "Merchant Name",
    amountLabel: "Amount (RM)",
    dateLabel: "Transaction Date",
    categoryLabel: "Category",
    saveTransaction: "✅ Save Transaction",
    confirmSave: "✅ Confirm & Save Transaction",
    notesLabel: "Personal Notes (optional)",
    successAdded: "Transaction saved — RM {amount} added to {category}",
    filters: "Top section — Filters",
    applyFilters: "Apply Filters",
    deleteSelected: "Delete Selected",
    manageCategories: "⚙️ Manage Categories",
    categoryName: "Category Name",
    budgetLimit: "Budget Limit",
    amountSpent: "Amount Spent",
    remaining: "Remaining",
    saveAllBudgets: "Save All Budgets",
    currentMonth: "Current Month",
    history: "History",
    totalSpent: "Total Spent",
    highestCategory: "Highest Category",
    mostFrequentMerchant: "Most Frequent Merchant",
    avgDailySpend: "Average Daily Spend",
    dailySpendingTrend: "Daily Spending Trend",
    totalSpentCategory: "Total Spent per Category",
    percentBreakdown: "% Breakdown by Category",
    downloadCsv: "📥 Download Report (CSV)",
    noAlertsDetected: "No anomalies detected this month 🎉",
    anomalyAlerts: "🚨 Anomaly Alerts",
    dismiss: "✅ Dismiss",
    reviewTx: "🔍 Review Transaction",
    aiForecast: "🤖 AI Spending Forecast",
    refreshForecast: "Refresh Forecast",
    confidenceCaption: "Based on your last 90 days of spending patterns",
    projectedSpend: "AI Projected Spend",
    onTrack: "✅ On Track",
    atRisk: "⚠️ At Risk",
    overBudget: "🔴 Over Budget"
  },
  bm: {
    dashboard: "🏠 Papan Pemuka",
    receiptEntry: "🧾 Kemasukan Resit & Transaksi",
    transactions: "🔀 Pengurusan Transaksi & Kategori",
    budgets: "🎯 Pengurusan Matlamat Bajet",
    reports: "📊 Laporan Perbelanjaan",
    forecastAlerts: "🤖 Ramalan AI & Amaran",
    logoSubtitle: "Belanja Pintar",
    userId: "Amirul Syafiq — Pelajar UM • 21 thn",
    langToggle: "English (EN)",
    totalSpentThisMonth: "Jumlah Belanja Bulan Ini",
    budgetRemaining: "Baki Bajet",
    txThisWeek: "Transaksi Minggu Ini",
    activeAlerts: "Amaran Aktif",
    spendingByCategory: "Belanja mengikut Kategori",
    budgetVsActual: "Bajet vs Sebenar mengikut Kategori",
    recentTransactions: "Transaksi Terkini",
    viewAll: "Lihat Semua Transaksi",
    uploadReceipt: "📤 Muat Naik Resit",
    ocrTab: "🔍 Muat Naik Resit OCR",
    manualTab: "✏️ Borang Data Manual",
    uploadReceiptLabel: "Muat naik resit anda (Seret & Lepas atau Cari)",
    cameraInputLabel: "Atau ambil gambar resit anda",
    extractingSpinner: "Mengekstrak data resit dengan Gemini OCR...",
    ocrResult: "Keputusan OCR",
    merchantName: "Nama Kedai/Peniaga",
    amountLabel: "Jumlah (RM)",
    dateLabel: "Tarikh Transaksi",
    categoryLabel: "Kategori",
    saveTransaction: "✅ Simpan Transaksi",
    confirmSave: "✅ Sahkan & Simpan Transaksi",
    notesLabel: "Nota Peribadi (pilihan)",
    successAdded: "Transaksi disimpan — RM {amount} ditambah ke {category}",
    filters: "Bahagian Atas — Penapis",
    applyFilters: "Guna Penapis",
    deleteSelected: "Padam Terpilih",
    manageCategories: "⚙️ Urus Kategori",
    categoryName: "Nama Kategori",
    budgetLimit: "Had Bajet",
    amountSpent: "Jumlah Dibelanjakan",
    remaining: "Baki Sisa",
    saveAllBudgets: "Simpan Semua Bajet",
    currentMonth: "Bulan Semasa",
    history: "Sejarah",
    totalSpent: "Jumlah Perbelanjaan",
    highestCategory: "Kategori Tertinggi",
    mostFrequentMerchant: "Peniaga Paling Kerap",
    avgDailySpend: "Purata Belanja Harian",
    dailySpendingTrend: "Trend Perbelanjaan Harian",
    totalSpentCategory: "Jumlah Belanja mengikut Kategori",
    percentBreakdown: "% Pecahan mengikut Kategori",
    downloadCsv: "📥 Muat Turun Laporan (CSV)",
    noAlertsDetected: "Tiada anomali dikesan bulan ini 🎉",
    anomalyAlerts: "🚨 Amaran Anomali",
    dismiss: "✅ Abai Amaran",
    reviewTx: "🔍 Semak Transaksi",
    aiForecast: "🤖 Ramalan Perbelanjaan AI",
    refreshForecast: "Segarkan Ramalan",
    confidenceCaption: "Berdasarkan corak perbelanjaan 90 hari terakhir anda",
    projectedSpend: "Ramalan Belanja AI",
    onTrack: "✅ Bersesuaian Jangkaan",
    atRisk: "⚠️ Berisiko Lebihan",
    overBudget: "🔴 Melebihi Bajet"
  }
};
